AWSTemplateFormatVersion: "2010-09-09"
Description: "Low interaction honeypot template"
Transform: AWS::Serverless-2016-10-31
Parameters:
  VpcId:
    Type: String
  SubnetId:
    Type: String
  KeyName:
    Type: String

Resources:
  Honeypot:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.nano
      ImageId: ami-07ad4b1c3af1ea214
      NetworkInterfaces:
        - NetworkInterfaceId:
            Ref: ManagementNetworkInterface
          DeviceIndex: 0
        - NetworkInterfaceId:
            Ref: MonitorNetworkInterface
          DeviceIndex: 1
      KeyName:
        Ref: KeyName
      IamInstanceProfile:
        Ref: EC2Profile

  # Elastic IP address
  MonitorIPAddr:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  ManagementIPAddr:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # Associations
  MonitorIPAddrAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::GetAtt: MonitorIPAddr.AllocationId
      NetworkInterfaceId:
        Ref: MonitorNetworkInterface
  MonitorNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Ref: SubnetId
      GroupSet:
        - Ref: MonitoringSG

  # Network interfaces
  ManagementIPAddrAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::GetAtt: ManagementIPAddr.AllocationId
      NetworkInterfaceId:
        Ref: ManagementNetworkInterface
  ManagementNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Ref: SubnetId
      GroupSet:
        - Ref: ManagementSG

  # Security groups
  ManagementSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "honeypot-mgmt"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
      VpcId:
        Ref: VpcId
  MonitoringSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "honeypot-monitoring"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
          FromPort: -1
          ToPort: -1
      VpcId:
        Ref: VpcId

  DataStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
          - "${StackName}-data-store"
          - StackName: {"Ref": "AWS::StackName"}
      NotificationConfiguration:
        TopicConfigurations:
        - Topic: {'Ref': 'DataStoreNotify'}
          Event: 's3:ObjectCreated:*'

  # --------------------------------------------------------
  # Instance Profile
  EC2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2Role

  # --------------------------------------------------------
  # IAM Roles
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["ec2.amazonaws.com"]
            Action: ["sts:AssumeRole"]
      Path: "/"
      Policies:
        - PolicyName: "S3Access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - Fn::GetAtt: DataStore.Arn
                  - Fn::Sub: [ "${BucketArn}/*", { BucketArn: { "Fn::GetAtt": DataStore.Arn } } ]

  DataStoreNotify:
    Type: AWS::SNS::Topic

  SNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ['s3.amazonaws.com']
          Action:
            - sns:Publish
          Resource:
            - Ref: DataStoreNotify
          Condition:
            ArnLike:
              aws:SourceArn:
                Fn::Sub:
                  - "arn:aws:s3:::${StackName}-data-store"
                  - StackName: {"Ref": "AWS::StackName"}
      Topics:
        - Ref: DataStoreNotify
